name: Knit readme and aggregate website JSONs

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'data/content/**'
      - 'data/packages/**'
      - 'README.Rmd'
      - 'scripts/generate_website_jsons.R'
      - '.github/workflows/knit_readme.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  knit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install cURL Headers
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "renv"

      - name: Setup renv
        uses: r-lib/actions/setup-renv@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Render readme files
        run: rmarkdown::render("README.Rmd", output_format = "github_document")
        shell: Rscript {0}

      - name: Aggregate website JSONs
        run: source("scripts/generate_website_jsons.R")
        shell: Rscript {0}

      - name: Generate app token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.JINX_APP_ID }}
          private-key: ${{ secrets.JINX_PRIVATE_KEY }}
          owner: rladies

      - name: Commit data
        env:
          GITHUB_PAT: ${{ steps.app-token.outputs.token }}
        run: |
          git config --local user.name "Jinx[bot]"
          git config --local user.email "jinx@rladies.org"
          git add README.md data/website
          git diff --cached --quiet || git commit -m 'Update README and aggregated website JSONs'
          git push origin || echo "Nothing to push"
